name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
      - "enhancement"
  patch:
    labels:
      - "patch"
      - "bug"
      - "chore"
  default: minor
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
  - title: "🤖 Dependencies"
    labels:
      - "dependencies"
    collapse-after: 1
  - title: "🔐 Security"
    labels:
      - "security"
exclude-labels:
  - "skip-changelog"
change-template: "* $TITLE @$AUTHOR (#$NUMBER)"
category-template: "##### $TITLE"
template: |
  $CHANGES
