name: Default

on:
  push:
    branches:
      - master

env:
  DOCKER_REGISTRY: ${{ secrets.VALKAMA_REGISTRY }}

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: elisa-normal
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Setup Mage
        uses: magefile/mage-action@v3
        with:
          install-only: true

      - name: Run go mod tidy
        run: go mod tidy

      - name: Test
        run: mage go:test

      - name: Build binary
        run: mage go:build

      - name: Login to docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.VALKAMA_USERNAME }}
          password: ${{ secrets.VALKAMA_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        env:
          DOCKER_IMAGE_TAGS: sha-${{ github.sha }}
        run: mage docker:build

      - name: Push image
        run: mage docker:push

  release_drafter:
    runs-on: elisa-normal
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Draft a release
        uses: elisa-actions/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          disable-releaser: false
          disable-autolabeler: true
