name: Pull Request
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}

jobs:
  test_and_build:
    concurrency:
      group: "${{ github.workflow }}-${{ github.ref }}-build"
      cancel-in-progress: true
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    runs-on: elisa-normal
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Setup mage
        uses: elisa-actions/setup-go-and-mage@v1

      - name: Ensure go.mod and go.sum are up-to-date
        run: mage go:tidyAndVerify

      - name: Test
        run: mage go:test

      - name: Build binary
        run: mage go:build

      - name: Build all binaries
        run: mage go:crossBuild

      - name: Login to docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        env:
          DOCKER_IMAGE_TAGS: sha-${{ github.sha }}
        run: mage docker:build
