name: Release
on:
  release:
    types:
      - published

env:
  DOCKER_REGISTRY: ${{ secrets.VALKAMA_REGISTRY }}

jobs:
  build:
    permissions:
      id-token: write
      contents: write
    runs-on: elisa-normal
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          check-latest: true
          cache: false

      - name: Setup Mage
        uses: magefile/mage-action@v3
        with:
          install-only: true

      - name: Run go mod tidy
        run: go mod tidy

      - name: Build docker binary
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: mage go:build

      - name: Login to docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.VALKAMA_USERNAME }}
          password: ${{ secrets.VALKAMA_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        env:
          DOCKER_IMAGE_TAGS: ${{ github.event.release.tag_name }}
        run: mage docker:build

      - name: Push image
        run: mage docker:push

      - name: Build all
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: mage go:crossBuild

      - name: Upload binaries
        uses: elisa-actions/action-gh-release@v2
        with:
          files: target/bin/*.tar.gz
